# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Alarm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alarm
pod ‘Fabric’
pod ‘Crashlytics’
pod 'CryptoSwift'
pod 'SnapKit'

end
